### ISSUE TITLE
Tutorial 2 on macOS doesn't appear to do anything

### ISSUE THREAD

**Issue by pornel** [sdroege/gstreamer-rs#59] opened 2017-11-12 00:12 UTC
```sh
cargo run --bin basic-tutorial-2
```
>     Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
>     Running `/www/gstreamer-rs/target/debug/basic-tutorial-2`

and it stays like that. I don't see any output, files, windows or any side effects of it running.

**Comment by sdroege** [comment] 2017-11-12 08:48
See https://github.com/sdroege/gstreamer-rs/issues/58#issuecomment-343722297 , I believe it's the same problem.

**Comment by philn** [comment] 2017-11-12 12:31
Yes, duplicate of #58

**Comment by pornel** [comment] 2017-11-12 12:32
```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00007fff6586ec76 libsystem_kernel.dylib`__pselect + 10
    frame #1: 0x00007fff6586ac27 libsystem_kernel.dylib`pselect$1050 + 82
    frame #2: 0x00000001001a9b30 libgstreamer-1.0.0.dylib`gst_poll_wait + 1568
    frame #3: 0x0000000100163588 libgstreamer-1.0.0.dylib`gst_bus_timed_pop_filtered + 856
    frame #4: 0x0000000100006732 basic-tutorial-2`gstreamer::auto::bus::{{impl}}::timed_pop(self=0x00007ffeefbff138, timeout=ClockTime @ 0x00007ffeefbff180) at bus.rs:116
    frame #5: 0x0000000100004e73 basic-tutorial-2`basic_tutorial_2::main at basic-tutorial-2.rs:35
    frame #6: 0x000000010002073f basic-tutorial-2`panic_unwind::__rust_maybe_catch_panic at lib.rs:99 [opt]
    frame #7: 0x0000000100015e19 basic-tutorial-2`std::rt::lang_start [inlined] std::panicking::try<(),closure> at panicking.rs:459 [opt]
    frame #8: 0x0000000100015de6 basic-tutorial-2`std::rt::lang_start [inlined] std::panic::catch_unwind<closure,()> at panic.rs:365 [opt]
    frame #9: 0x0000000100015de6 basic-tutorial-2`std::rt::lang_start at rt.rs:58 [opt]
    frame #10: 0x0000000100005615 basic-tutorial-2`main + 37
```

With #58 fixed I can hear tutorial 1 play sound, but no video. This might be the same.


```
/www/gstreamer-rs/target/debug/basic-tutorial-2:
	/Library/Frameworks/GStreamer.framework/Versions/1.0/lib/libgstreamer-1.0.0.dylib (compatibility version 1204.0.0, current version 1204.0.0)
	/Library/Frameworks/GStreamer.framework/Versions/1.0/lib/libgobject-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.3.0)
	/Library/Frameworks/GStreamer.framework/Versions/1.0/lib/libglib-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.3.0)
	/Library/Frameworks/GStreamer.framework/Versions/1.0/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by sdroege** [comment] 2017-11-12 12:38
Ok, same issue then. Thanks!

**Closed by sdroege** 2017-11-12 12:38 UTC
